FROM golang:1.20 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /waitfor ./cmd/waitfor

# Deploy the application binary into a lean image
FROM alpine:3 AS build-release-stage

WORKDIR /

COPY --from=build-stage /waitfor /waitfor

ENTRYPOINT ["/waitfor"]
