
version: '3.8'
services:
  db:
    ports:
      - 27017:27017

  pubsub:
    ports:
      - '8085:8085'

  test:
    command:
      - /bin/bash
      - -c
      - |
        echo "dependencies configured, up and running"
