name: CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: running CI
      run: make ci
    - name: Dump docker logs on failure
      if: failure()
      uses: jwalton/gh-docker-logs@v2